#!/bin/bash

scrot screenshot.png $1
bash puush screenshot.png
rm screenshot.png
text=$(qdbus-qt4 org.kde.klipper /klipper getClipboardContents)
kdialog --passivepopup "Screenshot puushed to $text" 3 --title "Puush" --icon "/home/pecto/puush-linux/puush.png"
